services:
  nextapp:
    container_name: nextapp
    image: nextapp:1.0
    build:
      context: ./frontend
      dockerfile: next.dockerfile
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    volumes:
      - ./frontend:/app
    depends_on:
      - goapp
  
  goapp:
    container_name: goapp
    image: goapp:1.0
    build:
      context: ./backend
      dockerfile: go.dockerfile
    environment:
      DATABASE_URL: 'sqlite:///app/internal/adapters/storage/db.sqlite'
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
