"use client";
import "../globals.css";
import ComplexNavbar from "../componants/navBar"
import LeftSide from "../componants/leftSide";
import RightSide from "../componants/rightSide";
import { useEffect, useState } from "react";
import { fetchData } from "../utils/fetch";
import WebsocketProvider from "@/module/websocket_provide";
import GroupIdProvider from "@/module/groupId_provide";
import HomeDataContext from "../api/context/HomeDataContext";
const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [homeData, setHomeData] = useState(null)
  useEffect(()=>{
    const loadPosts = async () => {
      setError(null);
      try {
        const fetchedData = await fetchData("/home"); // Assume this fetches the JSON you provided
        if (typeof fetchedData === "object" && fetchedData !== null) {
          setHomeData(fetchedData);
        } else {
          throw new Error('Data fetched is not an object');
        }
      } catch (error) {
        console.error('Error fetching data:', error);
        setError('Failed to fetch data. Please try again later.');
      } finally {
        setLoading(false);
      }
    };

    loadPosts();
  },[])

  return (
    <html lang="en">
      <body>
        <div className="pt-2">
          {loading ? (<div>Loading...</div>):error ? (<div>{error}</div>):(
            <WebsocketProvider>
              <GroupIdProvider>
                <ComplexNavbar />
                <div className="appContainer flex my-3 mx-6">
                  <div className="leftSide flex-none">
                    <LeftSide propsLeft={homeData}/>
                  </div>
                  <div className="mainContainer flex-auto flex justify-center pb-4">
                    <HomeDataContext.Provider value={homeData}>
                      {children}
                    </HomeDataContext.Provider>  
                  </div>
                  <div className="rightSide flex-none">
                    <RightSide propsRight={homeData}/>
                  </div>
                </div>
              </GroupIdProvider>
            </WebsocketProvider>
          )}
        </div>
      </body>
    </html>
  );
}
