CREATE TABLE IF NOT EXISTS follower (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    followerId INTEGER REFERENCES user(id),
    followeeId INTEGER REFERENCES user(id),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)