CREATE TABLE IF NOT EXISTS "member" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    userId INTEGER REFERENCES user(id),
    groupId INTEGER REFERENCES "group"(id),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)