CREATE TABLE IF NOT EXISTS event_reaction  (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    eventId INTEGER REFERENCES event(id),
    userId INTEGER REFERENCES user(id),
    issuedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);